spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:sqlserver://sql16ssd-005.localnet.kr:1433;encrypt=true;trustServerCertificate=true
    username: sonictmsdev_mssql
    password: sonicdb*3415

logging:
  config: classpath:log4j2-dev.xml
  level:
    com.sonictms: WARN

common:
  java:
    kppApiSearch: https://winus-interface.logisall.com:5201/restv2/WINUS.PAH:PAH_DLV_RR/PAH/DLV_ORDER
    kppApiStatus: https://winus-interface.logisall.com:5201/restv2/WINUS.PAH:PAH_DLV_RR/PAH/DLV_RTN_INSERT
    kppApiUsername: pahuser01
    kppApiUserpass: pahuser01
    bizMsgUrl: https://alimtalk-api.bizmsg.kr/v2/sender/send
    bizMsgUserid: alliance

mybatis:
  configuration-properties:
    schema: sonictmsdev_mssql
