create table dbo.TBL_INST_MOBILE_D
(
    INST_MOBILE_D_ID  bigint identity
        primary key,
    INST_MOBILE_M_ID  bigint,
    TBL_SO_M_ID       bigint,
    TBL_SO_P_ID       bigint,
    PROD_CD           varchar(100),
    PROD_NM           varchar(200),
    QTY               int,
    PROD_STAT_CD      varchar(50),
    INST_COST         int,
    DLVY_COST         int,
    PROD_LIFT_CMPL_YN varchar(10),
    UPDT_USER         varchar(30),
    UPDT_TIME         datetime,
    SAVE_USER         varchar(30),
    SAVE_TIME         datetime,
    INST_URL          varchar(200),
    INST_IMG_PATH     varchar(200)
);

create table dbo.TBL_INST_MOBILE_LIFT_D
(
    MOBILE_LIFT_ID   bigint identity,
    INST_MOBILE_M_ID bigint,
    INST_MOBILE_D_ID bigint,
    LIFT_QTY         bigint,
    LIFT_DT          varchar(10),
    INPT_USER_ID     bigint,
    INPT_TIME        datetime,
    USE_YN           varchar(10),
    SAVE_USER        varchar(30),
    SAVE_TIME        datetime,
    UPDT_USER        varchar(30),
    UPDT_TIME        datetime
);

create table dbo.TBL_SO_M
(
    TBL_SO_M_ID         bigint identity
        primary key,
    CMPY_CD             varchar(10),
    SO_NO               varchar(100),
    REF_SO_NO           varchar(100),
    SO_TYPE             varchar(20),
    SO_STAT_CD          varchar(20),
    AGNT_CD             varchar(10),
    DIST_CHAN_CD        varchar(20),
    MALL_CD             varchar(50),
    BRAND               varchar(20),
    ORDR_ER             varchar(50),
    ACPT_ER             varchar(50),
    ACPT_TEL1           varchar(20),
    ACPT_TEL2           varchar(20),
    POST_CD             varchar(10),
    ADDR1               varchar(200),
    ADDR2               varchar(200),
    ADDR1_OLD           varchar(100),
    ADDR2_OLD           varchar(200),
    FROM_ER             varchar(10),
    FROM_TEL1           varchar(20),
    FROM_TEL2           varchar(20),
    FROM_POST_CD        varchar(10),
    FROM_ADDR1          varchar(200),
    FROM_ADDR2          varchar(200),
    ORDR_INPT_DT        varchar(10),
    ORDR_INPT_ER        varchar(20),
    ORDR_INPT_TIME      datetime,
    RCPT_DT             varchar(10),
    RQST_DT             varchar(10),
    RQST_INPT_ER        varchar(20),
    RQST_INPT_TIME      datetime,
    DLVY_CNFM_DT        varchar(10),
    DLVY_CNFM_INPT_ER   varchar(20),
    DLVY_CNFM_INPT_TIME datetime,
    INPT_SYS            varchar(20),
    ORGN_SO_NO          varchar(50),
    DLVY_RQST_MSG       varchar(1000),
    CUST_SPCL_TXT       varchar(500),
    DLVY_COST_TYPE      varchar(10),
    RCPT_COST           int,
    PASS_COST           int,
    USE_YN              varchar(10),
    DEL_RESN            varchar(100),
    MEMO                varchar(200),
    SAVE_USER           varchar(30),
    SAVE_TIME           datetime,
    UPDT_USER           varchar(30),
    UPDT_TIME           datetime,
    DC_CD               varchar(20),
    ZONE_CD             varchar(50),
    ZONE_TYPE           varchar(50),
    GI_LIFT_DT          varchar(10),
    GI_LIFT_INPT_ER     varchar(10),
    GI_LIFT_INPT_TIME   datetime,
    AGNT_DEPT_CD        varchar(50),
    OUT_CMPY_CD         varchar(10),
    OUT_DLV_ORD_ID      varchar(20),
    OUT_DLV_ORD_SEQ     varchar(20),
    OUT_DLV_ORD_SUBSEQ  varchar(20)
)

create table dbo.TBL_INV_PRODUCT
(
    TBL_INV_PRODUCT_ID bigint identity
        primary key,
    CMPY_CD            varchar(10),
    AGNT_CD            varchar(10),
    AGNT_NM            varchar(50),
    TBL_MTRL_M_ID      bigint,
    MTRL_CD            varchar(100),
    MTRL_NM            varchar(500),
    CURRENT_QTY        int,
    SAVE_TIME          datetime,
    SAVE_USER          varchar(100),
    UPDT_TIME          datetime,
    UPDT_USER          varchar(100)
)

create table dbo.TBL_INV_ADJUSTMENT
(
    TBL_INV_ADJUSTMENT_ID bigint identity
        primary key,
    CMPY_CD               varchar(10)  not null,
    AGNT_CD               varchar(10)  not null,
    AGNT_NM               varchar(50),
    TBL_MTRL_M_ID         bigint,
    MTRL_CD               varchar(100) not null,
    MTRL_NM               varchar(500),
    ADJUSTMENT_TYPE       varchar(10)  not null,
    BEFORE_QTY            int          not null,
    ADJUSTMENT_QTY        int          not null,
    AFTER_QTY             int          not null,
    ADJUSTMENT_REASON     varchar(500),
    ADJUSTMENT_DATE       date         not null,
    SAVE_TIME             datetime     not null,
    SAVE_USER             varchar(100) not null,
    UPDT_TIME             datetime,
    UPDT_USER             varchar(100),
    DELETED_YN            varchar default 'N'
)

create table TBL_MTRL_M
(
    TBL_MTRL_M_ID              bigint identity
        primary key,
    CMPY_CD                    varchar(10),
    AGNT_CD                    varchar(10),
    MTRL_TYPE                  varchar(50),
    MTRL_CD                    varchar(100),
    MTRL_NM                    varchar(200),
    MTRL_DESC                  varchar(500),
    STAT_CD                    varchar(10),
    SMPL_CD                    varchar(50),
    CUST_PRC                   int,
    SALE_PRC                   int,
    FACT_PRC                   int,
    PURC_PRC                   int,
    SIZE_NM                    varchar(100),
    LNTH                       int,
    DPTH                       int,
    HGHT                       int,
    HGHT2                      int,
    CBM                        float,
    WGHT                       int,
    MTRL_CTGR_1                varchar(50),
    MTRL_CTGR_2                varchar(50),
    MTRL_CTGR_3                varchar(50),
    SET_YN                     varchar(10),
    BOM_YN                     varchar(10),
    MTO_YN                     varchar(10),
    STD_YN                     varchar(10),
    INST_YN                    varchar(10),
    INST_TYPE                  varchar(50),
    INST_COST                  int,
    INST_URL                   varchar(200),
    INST_IMG_PATH              varchar(200),
    PSTN_NM                    varchar(50),
    DLVY_YN                    varchar(10),
    DLVY_TYPE                  varchar(50),
    DLVY_COST                  int,
    NDLVY_YN                   varchar(10),
    THR_DLVY_YN                varchar(10),
    DLVY_LT                    int,
    CNVT_MTRL_CD               varchar(100),
    CNVT_MTRL_NM               varchar(200),
    CNVT_QTY                   int,
    CNVT_UNIT                  varchar(10),
    MEMO                       varchar(100),
    USE_YN                     varchar(10),
    SAVE_USER                  varchar(30),
    SAVE_TIME                  datetime,
    UPDT_USER                  varchar(30),
    UPDT_TIME                  datetime,
    INST_SEAT_TYPE             varchar(50),
    INST_CTGR                  varchar(50),
    ZONE_TYPE                  varchar(20),
    PICK_ZONE                  varchar(50),
    EXCHANGE_RETURN_EXCLUDE_YN char default 'N'
)

create table dbo.TBL_SO_HIST
(
    HIST_ID         bigint identity
        primary key,
    TBL_SO_M_ID     bigint,
    UPDT_BEFORE_TXT varchar(1000),
    UPDT_AFTER_TXT  varchar(1000),
    UPDT_EVENT_TXT  varchar(1000),
    SAVE_USER       varchar(30),
    SAVE_DATE       datetime
)

create table dbo.TBL_SO_P
(
    TBL_SO_P_ID            bigint identity
        primary key,
    TBL_SO_M_ID            bigint,
    SO_NO                  varchar(100),
    PROD_SEQ               int,
    PROD_CD                varchar(100),
    PROD_NM                varchar(200),
    QTY                    int,
    UNIT                   varchar(10),
    CUST_PRC               float,
    SALE_PRC               float,
    FACT_PRC               float,
    PURC_PRC               float,
    DC_PRC                 float,
    SIZE_NM                varchar(100),
    L                      int,
    D                      int,
    H                      int,
    H2                     int,
    MTRL_CTGR_1            varchar(50),
    MTRL_CTGR_2            varchar(50),
    MTRL_CTGR_3            varchar(50),
    SET_YN                 varchar(10),
    BOM_YN                 varchar(10),
    NSPEC_YN               varchar(10),
    INST_YN                varchar(10),
    INST_CTGR              varchar(50),
    INST_TYPE              varchar(50),
    INST_COST              int,
    INST_SEAT_TYPE         varchar(50),
    ZONE_TYPE              varchar(50),
    ZONE_CD                varchar(50),
    DLVY_YN                varchar(10),
    DLVY_TYPE              varchar(50),
    DLVY_COST              int,
    DC_CD                  varchar(10),
    RQST_DT                varchar(10),
    RQST_MSG               varchar(200),
    DLVY_CNFM_DT           varchar(10),
    NDLVY_YN               varchar(10),
    THR_DLVY_YN            varchar(10),
    CNVT_MTRL_CD           varchar(100),
    CNVT_MTRL_NM           varchar(200),
    CNVT_QTY               int,
    CNVT_UNIT              varchar(10),
    USE_YN                 varchar(10),
    DEL_RESN               varchar(100),
    MEMO                   varchar(100),
    SAVE_USER              varchar(30),
    SAVE_TIME              datetime,
    UPDT_USER              varchar(30),
    UPDT_TIME              datetime,
    CBM                    float,
    WGHT                   float,
    GI_LIFT_DT             varchar(10),
    REF_SO_NO              varchar(100),
    DLVY_COST_TYPE         varchar(10),
    RCPT_COST              int,
    PASS_COST              int,
    OUT_DLV_ORD_ID         varchar(20),
    OUT_DLV_ORD_SEQ        varchar(20),
    OUT_DLV_ORD_SUBSEQ     varchar(20),
    YONGIN_INBOUNDED       varchar(10),
    YONGIN_INBOUND_DT      varchar(10),
    YONGIN_INBOUND_TIME    datetime,
    YONGIN_INBOUND_USER    varchar(30),
    YONGIN_INBOUND_REMARK  varchar(500),
    AGENCY_OUTBOUNDED      varchar(10),
    AGENCY_OUTBOUND_DT     varchar(10),
    AGENCY_OUTBOUND_TIME   datetime,
    AGENCY_OUTBOUND_USER   varchar(30),
    AGENCY_OUTBOUND_REMARK varchar(500),
    IS_OUTBOUND_TARGET     varchar(10) default 'Y',
    RESTOCK_INBOUNDED      varchar(10) default 'N',
    RESTOCK_INBOUND_DT     varchar(10),
    RESTOCK_INBOUND_TIME   datetime,
    RESTOCK_INBOUND_USER   varchar(100)
)

create table dbo.TBL_INST_MOBILE_M
(
    INST_MOBILE_M_ID bigint identity
        constraint PK__TBL_INST__542627D93513E1A5
            primary key,
    INST_PLAN_ID     bigint,
    TBL_SO_M_ID      bigint,
    CMPY_CD          varchar(10),
    INST_DT          varchar(10),
    AGNT_CD          varchar(10),
    DC_CD            varchar(10),
    INST_CMPY        varchar(50),
    PLAN_USER_M_ID   bigint,
    EXEC_USER_M_ID   bigint,
    SO_NO            varchar(100),
    REF_SO_NO        varchar(100),
    SO_TYPE          varchar(10),
    DLVY_STAT_CD     varchar(10),
    DLVY_TYPE_CD     varchar(10),
    INST_CTGR        varchar(50),
    INST_TYPE        varchar(50),
    SEAT_TYPE        varchar(50),
    ZONE_TYPE        varchar(50),
    ZONE_CD          varchar(50),
    INST_STAT_CD     varchar(50),
    PALT_NOXX        varchar(20),
    SEQ              int,
    ORDR_ER          varchar(50),
    ACPT_ER          varchar(50),
    ACPT_TEL1        varchar(20),
    ACPT_TEL2        varchar(20),
    POST_CD          varchar(10),
    ADDR1            varchar(200),
    ADDR2            varchar(200),
    DLVY_RQST_MSG    varchar(1000),
    CUST_SPCL_TXT    varchar(500),
    TEL_CNT          int,
    CBM              float,
    INST_COST        int,
    DLVY_COST_TYPE   varchar(20),
    RCPT_COST        int,
    PASS_COST        int,
    DLVY_COST        int,
    AGNT_HP          varchar(20),
    LIFT_CMPL_YN     varchar(10),
    HPCL_CMPL_YN     varchar(10),
    DLVY_CMPL_YN     varchar(10),
    DLVY_CLCL_YN     varchar(10),
    DLVY_PSTP_YN     varchar(10),
    DLVY_NCMPL_YN    varchar(10),
    UPDT_USER        varchar(30),
    UPDT_TIME        datetime,
    SAVE_USER        varchar(30),
    SAVE_TIME        datetime,
    DLVY_CMPL_DT     varchar(10)
)

create table dbo.TBL_INST_MOBILE_D
(
    INST_MOBILE_D_ID  bigint identity
        primary key,
    INST_MOBILE_M_ID  bigint,
    TBL_SO_M_ID       bigint,
    TBL_SO_P_ID       bigint,
    PROD_CD           varchar(100),
    PROD_NM           varchar(200),
    QTY               int,
    PROD_STAT_CD      varchar(50),
    INST_COST         int,
    DLVY_COST         int,
    PROD_LIFT_CMPL_YN varchar(10),
    UPDT_USER         varchar(30),
    UPDT_TIME         datetime,
    SAVE_USER         varchar(30),
    SAVE_TIME         datetime,
    INST_URL          varchar(200),
    INST_IMG_PATH     varchar(200)
)

create table dbo.TBL_INST_MOBILE_LIFT_D
(
    MOBILE_LIFT_ID   bigint identity,
    INST_MOBILE_M_ID bigint,
    INST_MOBILE_D_ID bigint,
    LIFT_QTY         bigint,
    LIFT_DT          varchar(10),
    INPT_USER_ID     bigint,
    INPT_TIME        datetime,
    USE_YN           varchar(10),
    SAVE_USER        varchar(30),
    SAVE_TIME        datetime,
    UPDT_USER        varchar(30),
    UPDT_TIME        datetime
)

create table dbo.TBL_INST_MOBILE_COMPLETE
(
    MOBILE_COMPLETE_ID bigint identity,
    INST_MOBILE_M_ID   bigint,
    DLVY_COST_CLCT     varchar(10),
    DLVY_COST_TXT      varchar(50),
    LIFT_COST_YN       varchar(10),
    LIST_COST_TXT      varchar(50),
    DOWN_SRVC_YN       varchar(10),
    DOWN_SRVC_TXT      varchar(50),
    WALL_FSTN_YN       varchar(10),
    WALL_FSTN_TXT      varchar(50),
    MEMO               varchar(600),
    SIGN_IMG           varchar(500),
    IMG1               varchar(500),
    IMG2               varchar(500),
    IMG3               varchar(500),
    IMG4               varchar(500),
    IMG5               varchar(500),
    IMG6               varchar(500),
    IMG7               varchar(500),
    IMG8               varchar(500),
    IMG9               varchar(500),
    IMG10              varchar(500),
    USE_YN             varchar(10),
    BIGO               varchar(600),
    SAVE_USER          varchar(30),
    SAVE_TIME          datetime,
    UPDT_USER          varchar(30),
    UPDT_TIME          datetime
)
