CREATE PROCEDURE [dbo].[USP_SO_OUT_CMPY_IF_SO_STAT_UPDT_LISTBYALL] (
@I_SO_NO_LIST	VARCHAR(MAX)   -- 주문번호
,@I_SO_STAT_CD	VARCHAR(100)   -- 변경할 주문상태
,@I_DEL_RESN  VARCHAR(100)     -- 삭제사유
)
/**********************************
1. 목적&기능 : KPP(외부사) 주문상태 변경을 위한 REQUEST 값 가져오기
2. 변경 내용 및 사유 :
3. 실행예시 :

-- 주문삭제시
USP_SO_OUT_CMPY_IF_SO_STAT_UPDT_LISTBYALL '2204280001,2204280002,2204280003','0000','취소사유-테스'
USP_SO_OUT_CMPY_IF_SO_STAT_UPDT_LISTBYALL '2204280001','0000','취소사유-테스'

-- 주문상태변경시
USP_SO_OUT_CMPY_IF_SO_STAT_UPDT_LISTBYALL '2204280001,2204280002,2204280003','0000',''
USP_SO_OUT_CMPY_IF_SO_STAT_UPDT_LISTBYALL '2204280001','0000',''



SELECT * FROM TBL_SO_M WHERE SO_NO IN ('2204280001','2204280002','2204280003' )

SP_HELPTEXT USP_SO_ALLUPDATE_DEL
SELECT * FROM TBL_SO_M WHERE OUT_CMPY_CD = 'KPP'


DLV_ORD_ID				VARCHAR2	20	NOT NULL		배송주문번호(WINUS)	0000980998
DLV_ORD_SEQ				VARCHAR2	20	NOT NULL		배송주문SEQ	1
IMG_SND_YN				VARCHAR2	1					이미지여부	 Y/N
DLV_REQ_DT				VARCHAR2	8					배송예정일	20220503
DLV_SET_DT				VARCHAR2	8					배송완료일	20220503
SET_DRIVER_ID			VARCHAR2	20					지정배송기사	송우용SM
SET_DRIVER_TL			VARCHAR2	20					기사전화번호	010-9446-1232
DLV_ORD_STAT			VARCHAR2	20	NOT NULL		배송상태	'배송상태 코드 매칭'!A1
DLV_ORD_STAT_NM			VARCHAR2	20	NOT NULL		배송상태명	'배송상태 코드 매칭'!A1
ETC2					VARCHAR2	1000				취소사유
SERIAL_NO				VARCHAR2	50					시리얼번호
DLV_COMMENT				VARCHAR2	1000				배송메모모바일
MEMO					VARCHAR2	1000				인수증메모
LIFTING_WORK_YN			VARCHAR2	1					양중여부	 Y/N
HAPPY_CALL_YN			VARCHAR2	1					해피콜여부	 Y/N
HAPPY_CALL_MEMO			VARCHAR2	1000				해피콜메모
HAPPY_CALL_DT			VARCHAR2	20					해피콜일자	2022-05-04 09:26:40
MOBILE_COM_DT			VARCHAR2	20					모바일완료일	2022-05-04 09:26:40
PRINT_RECEIPT_YN		VARCHAR2	1					인수증출력확인	 Y/N
MOBILE_COM_ID			VARCHAR2	20					모바일완료자	송우용SM
**********************************/
AS
SET NOCOUNT ON
SET LOCK_TIMEOUT 60000
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN
------------------------------------------------------------------
SELECT	DISTINCT
    SM.OUT_DLV_ORD_ID							AS DLV_ORD_ID 			--배송주문번호(WINUS)
                 ,SM.OUT_DLV_ORD_SEQ						AS DLV_ORD_ID_SEQ		--배송주문SEQ	1  --20220517 정연호 수정 SLV 를 DLV로 수정함
                 ,'N'										AS IMG_SND_YN			--이미지여부	 Y/N
                 ,SM.DLVY_CNFM_DT							AS DLV_REQ_DT			--배송예정일	2022
                 ,SM.DLVY_CNFM_DT							AS DLV_SET_DT								--배송완료일	2022
                 ,ISNULL(ISNULL(UM2.USER_NM,UM.USER_NM),'')	AS SET_DRIVER_ID							--지정배송기사
                 ,ISNULL(ISNULL(UM2.HP,UM.HP),'')			AS SET_DRIVER_TL							--기사전화번호
              --배송상태	'배송
                 , DLV_ORD_STAT = (SELECT TOP 1 X.ORGN_CD FROM TBL_SO_OUT_CMPY_MAPPING_CD X WITH(NOLOCK) WHERE X.OUT_CMPY_CD ='KPP' AND X.MAPPING_TYPE_CD ='SO_STAT_CD' AND  X.CNVT_CD = @I_SO_STAT_CD )

FROM DBO.TBL_SO_M AS SM WITH(NOLOCK)
    --20220608 정연호 6월 8일 개발과 운영이 다르다는것을 발견함 --이건 개발에 있던것
    LEFT OUTER JOIN TBL_INST_PLAN_M AS PM WITH(NOLOCK) ON  SM.TBL_SO_M_ID = PM.TBL_SO_M_ID
    LEFT OUTER JOIN TBL_INST_MOBILE_M AS MM WITH(NOLOCK) ON SM.TBL_SO_M_ID = MM.TBL_SO_M_ID

    --20220608 정연호 6월 8일 개발과 운영이 다르다는것을 발견함 --이건 운영에 있던것
    --LEFT OUTER JOIN TBL_INST_PLAN_M AS PM WITH(NOLOCK) ON SM.SO_NO = PM.SO_NO AND SM.TBL_SO_M_ID = PM.TBL_SO_M_ID
    --LEFT OUTER JOIN TBL_INST_MOBILE_M AS MM WITH(NOLOCK) ON PM.SO_NO = MM.SO_NO AND SM.TBL_SO_M_ID = MM.TBL_SO_M_ID AND PM.TBL_SO_M_ID = MM.TBL_SO_M_ID

    LEFT OUTER JOIN TBL_INST_MOBILE_HAPPYCALL  AS MH WITH(NOLOCK) ON MM.INST_MOBILE_M_ID = MH.INST_MOBILE_M_ID
    LEFT OUTER JOIN TBL_INST_MOBILE_COMPLETE   AS MC WITH(NOLOCK) ON MM.INST_MOBILE_M_ID =  MC.INST_MOBILE_M_ID
    LEFT OUTER JOIN TBL_INST_MOBILE_X_COMPLETE AS XMC WITH(NOLOCK) ON MM.INST_MOBILE_M_ID = XMC.INST_MOBILE_M_ID

    LEFT OUTER JOIN TBL_USER_M AS UM WITH(NOLOCK) ON PM.TBL_USER_M_ID = UM.TBL_USER_M_ID
    LEFT OUTER JOIN TBL_USER_M AS UM2 WITH(NOLOCK) ON MM.EXEC_USER_M_ID = UM2.TBL_USER_M_ID



WHERE 1=1
  AND SM.SO_NO = @I_SO_NO_LIST
--AND SM.TBL_SO_M_ID = @I_SO_NO_LIST


--  AND EXISTS (SELECT 1 FROM DBO.SPLIT_STR (ISNULL(@I_TBL_SO_M_ID_LIST,''),',') AS T
--					WHERE T.VAL = SM.TBL_SO_M_ID
--			UNION ALL	SELECT 1 WHERE ISNULL(@I_TBL_SO_M_ID_LIST, '') ='' )






/*			------------------------------------------------------------------------------------------------------
--AND SM.SO_NO IN ('2205040004','2205040005')



    TBL_INST_MOBILE_X_COMPLETE
    TBL_INST_MOBILE_HAPPYCALL
    TBL_INST_MOBILE_LIFT_D

    SELECT TOP 1000 * FROM TBL_INST_MOBILE_M
    SELECT TOP 1000 * FROM TBL_INST_MOBILE_D
    SELECT TOP 1000 * FROM TBL_INST_MOBILE_X_COMPLETE
    SELECT TOP 1000 * FROM TBL_INST_MOBILE_HAPPYCALL

    SELECT TOP 1000 * FROM TBL_INST_MOBILE_LIFT_D
    SELECT TOP 1000 * FROM TBL_INST_MOBILE_COMPLETE

    SP_HELP TBL_INST_MOBILE_HAPPYCALL
    SP_HELP TBL_INST_MOBILE_M

    SP_HELP TBL_INST_MOBILE_HAPPYCALL
    SP_HELP TBL_INST_MOBILE_COMPLETE
    SP_HELP TBL_INST_MOBILE_X_COMPLETE

    CREATE NONCLUSTERED INDEX NX_SAVE_TIME ON TBL_INST_MOBILE_HAPPYCALL (SAVE_TIME)

    CREATE NONCLUSTERED INDEX NX_SAVE_TIME ON TBL_INST_MOBILE_COMPLETE (SAVE_TIME)
    CREATE NONCLUSTERED INDEX NX_SAVE_TIME ON TBL_INST_MOBILE_X_COMPLETE (SAVE_TIME)


    */


END -- SP 종료


go

