CREATE PROCEDURE [dbo].[USP_SO_P_DEL] (					
 @I_TBL_SO_M_ID		BIGINT
,@I_TBL_SO_P_ID		BIGINT
,@I_USE_YN			VARCHAR(10)
,@I_DEL_RESN		VARCHAR(100)
,@I_MEMO			VARCHAR(100)
,@I_SAVE_USER		VARCHAR(30)
)
/**********************************					
1. 목적&기능 : 주문정보 (품목삭제하기)
2. 변경 내용 및 사유 :					
3. 실행예시 :			

USP_SO_P_DEL 26617,60154,'N','품목삭제','','AVENGERS'

SELECT * FROM USP_SO_P_UPDT
SELECT * FROM TBL_SO_M
SELECT * FROM TBL_SO_P WHERE TBL_SO_M_ID = 26617


		
**********************************/					
AS					
SET NOCOUNT ON					
SET LOCK_TIMEOUT 60000					
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN	

	-- 삭제할 상품 정보 조회
	DECLARE @PROD_CD VARCHAR(50)
	DECLARE @SO_TYPE VARCHAR(50)

SELECT @PROD_CD = P.PROD_CD,
       @SO_TYPE = M.SO_TYPE
FROM TBL_SO_P P WITH(NOLOCK)
	INNER JOIN TBL_SO_M M WITH(NOLOCK) ON P.TBL_SO_M_ID = M.TBL_SO_M_ID
WHERE P.TBL_SO_M_ID = @I_TBL_SO_M_ID
  AND P.TBL_SO_P_ID = @I_TBL_SO_P_ID

UPDATE P SET
    USE_YN		= @I_USE_YN
           ,UPDT_USER	= @I_SAVE_USER
           ,DEL_RESN	= @I_DEL_RESN
           ,UPDT_TIME	= GETDATE()
    FROM TBL_SO_P AS P WITH(NOLOCK)
WHERE 1=1
  AND P.TBL_SO_M_ID = @I_TBL_SO_M_ID
  AND P.TBL_SO_P_ID = @I_TBL_SO_P_ID

-- TBL_SO_P UPDATE 결과 확인 (MERGE 이전에 저장)
DECLARE @UPDATE_COUNT INT
SELECT @UPDATE_COUNT = @@ROWCOUNT
	
	IF(@UPDATE_COUNT = 1)
BEGIN
SELECT 	'Y' AS  RTN_YN  , '삭제완료' AS RTN_MSG
END
ELSE
BEGIN
SELECT 	'N' AS  RTN_YN  , '삭제실패' AS RTN_MSG
END

END
go

