CREATE PROCEDURE [dbo].[USP_SO_P_UPDT](
    @I_TBL_SO_P_ID BIGINT
, @I_REF_SO_NO VARCHAR(100)
, @I_DLVY_COST_TYPE VARCHAR(100) --운임구분
, @I_RCPT_COST INT --착불비
, @I_PASS_COST INT --통행비
, @I_SAVE_USER VARCHAR(30)
, @I_QTY INT --= NULL
)
/**
1. 목적&기능 : 주문상세 수정
3. 실행예시 :
SELECT * FROM TBL_SO_M

SELECT * FROM TBL_SO_P
*/
AS
    SET NOCOUNT ON
    SET LOCK_TIMEOUT 60000
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN

    UPDATE A
    SET REF_SO_NO      = @I_REF_SO_NO,
        DLVY_COST_TYPE = @I_DLVY_COST_TYPE,
        RCPT_COST      = @I_RCPT_COST,
        PASS_COST      = @I_PASS_COST,
        UPDT_USER      = @I_SAVE_USER,
        UPDT_TIME      = GETDATE(),
        QTY            = @I_QTY
    FROM TBL_SO_P A
    WHERE 1 = 1
      AND TBL_SO_P_ID = @I_TBL_SO_P_ID

    SELECT 'Y' AS RTN_YN, '변경완료' AS RTN_MSG
END
go

